### ISSUE TITLE
Visual Studio 2012 - Include latest update in install process

### ISSUE THREAD

**Issue by Thieum** [mwrock/Chocolatey-Packages#21]
Would it be possible to include the latest update in the chocolatey package for VS 2012 ? 
The directlink is this:

http://download.microsoft.com/download/D/4/8/D48D1AC2-A297-4C9E-A9D0-A218E6609F06/VSU4/VS2012.4.exe

Or would it be better to create a separate package?

**Comment by ryanewtaylor** [comment]
I have a similar question (which I posted on the [Visual Studio 2012 Professional Page](https://chocolatey.org/packages/VisualStudio2012Professional)). Update 5 is now available. It would be really helpful if this package was updated to install the latest version of Visual Studio. Should this enhancement be made to the existing package, or a new one?

**Comment by mwrock** [comment]
I think an update to this package would be best. Happy to accept a PR and push it to the chocolatey feed.

**Comment by Thieum** [comment]
Packages have been created for both update 4 and 5:
https://chocolatey.org/packages/VS2012.4
https://chocolatey.org/packages/vs2012.5
