### ISSUE TITLE
DotNet3.5 on Windows 11

### ISSUE THREAD

**Issue by Aurocosh** [mwrock/Chocolatey-Packages#65]
The DotNet3.5 package is broken on Windows 11. The DotNet3.5 package uses WMIC, and the WMIC utility is currently deprecated in Windows 11.

**Comment by corbob** [comment]
I've thrown up a PR that should resolve this issue. In the mean time, some links that others finding this might find useful:
- [Instructions to install `wmic` on Windows 11](https://techcommunity.microsoft.com/blog/windows-itpro-blog/how-to-install-wmic-feature-on-demand-on-windows-11/4189530)
- [Information from Microsoft regarding the deprecation (in 2016) and removal of `wmic`](https://techcommunity.microsoft.com/blog/windows-itpro-blog/wmi-command-line-wmic-utility-deprecation-next-steps/4039242)

**Comment by Aurocosh** [comment]
Thank you for the fix. I have become a maintainer of this package and updated it with the fix from your pull request.
